name: Release

on: 
    workflow_dispatch:

jobs:
    release:
        permissions: 
            contents: write
            issues: write
            pull-requests: write
        runs-on: ubuntu-latest
        steps: 
           - uses: actions/checkout@v2
           - uses: actions/setup-node@v2
             with:
                node-version: 16
           - run: npm c1
           - run: npm run build
           - run: npx semantic-release
             env: 
                GITHUB_TOKE: ${{ secrets.GITHUB_TOKEN }}